remote_theme: pages-themes/cayman@v0.2.0
plugins:
- <a href="http://www.linkedin.com/in/ananya-mukherjee002">LinkedIn</a>
title: Ananya's Data Portfolio
description: Transforming raw data to dynamic dashboards
